apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-model
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock-model
  template:
    metadata:
      labels:
        app: stock-model
    spec:
      containers:
      - name: stock-model
        image: stock-model
        imagePullPolicy: Never  # Uses local image
        ports:
        - containerPort: 8000